name: create-map
on: push

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./github/workflows/man.sh
         ./github/workflows/man.sh
      shell: bash
