name: create-map
on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         cd ~
         git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8
         export ARCH=arm
         export CROSS_COMPILE=~/arm-eabi-4.8/bin/arm-eabi-
         make clean 
         make mt6737t-grandpplte
      shell: bash
