me: "Build Dark Ages kernel on darky."              # Description of the workflow.
on:
  push:
    branches: 3.18.53-N                                   # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build Dark Ages kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
      uses: actions/checkout@v2
      with:
        repository: lemniskett/AnyKernel3             # Your own AnyKernel3 repository.
        path: zipper                                  # Clone to path "zipper", REQUIRED.
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm                                   # Specify arch
        compiler: gcc/9                               # Specify toolchain to use
        defconfig: mt6737t-grandpplte                    # Specify defconfig to use
        image: zImage                           # Specify final build file

1625464988_grim.png
